name: Release
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
      - uses: actions/checkout@v3
      - run: chmod +x ./gradlew

      - name: Build and Publish Artifacts
        uses: gradle/gradle-build-action@v2
        with:  
          arguments: build checkLicenses publish curseforge modrinth --stacktrace
          gradle-home-cache-cleanup: true

        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ github.event.release.body }}

      - name: Upload artifacts to GitHub
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/libs/*.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
