name: Publish Snapshot
on:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        java: [17]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - uses: actions/checkout@v3
      - run: chmod +x ./gradlew
      - run: ./gradlew checkLicenses --parallel --stacktrace
      - run: ./gradlew build publish --stacktrace --parallel
        env:
          SNAPSHOTS_URL: ${{ secrets.SNAPSHOTS_URL }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          SNAPSHOTS_PASSWORD: ${{ secrets.SNAPSHOTS_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./*/build/libs/