name: Publish Snapshot
on:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        java: [21]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - uses: actions/checkout@v3
      - run: chmod +x ./gradlew

      - name: Build Artifacts
        uses: gradle/gradle-build-action@v2
        with:  
          arguments: build checkLicenses publish --stacktrace
          gradle-home-cache-cleanup: true

        env:
          SNAPSHOTS_URL: ${{ secrets.SNAPSHOTS_URL }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          SNAPSHOTS_PASSWORD: ${{ secrets.SNAPSHOTS_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./*/build/libs/