name: Test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [21]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          
      - uses: actions/checkout@v3
      - run: chmod +x ./gradlew

      - name: Build Artifacts
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build checkLicenses --stacktrace
          gradle-home-cache-cleanup: true

      - uses: actions/upload-artifact@v3
        with:
          name: Built Artifacts
          path: |
            ./**/build/libs/